version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    working_directory: ~/hello-react
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install

workflows:
    build:
      jobs:
        - build